//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMINISTRADOR
    {
        public ADMINISTRADOR()
        {
            this.SERVICIOCOMEDOR = new HashSet<SERVICIOCOMEDOR>();
            this.HABITACION = new HashSet<HABITACION>();
        }
    
        public decimal IDADMINISTRADOR { get; set; }
        public decimal USUARIO { get; set; }
    
        public virtual ICollection<SERVICIOCOMEDOR> SERVICIOCOMEDOR { get; set; }
        public virtual ICollection<HABITACION> HABITACION { get; set; }
        public virtual USUARIO USUARIO1 { get; set; }
    }
}
