//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public decimal IDCLIENTE { get; set; }
        public string RUT { get; set; }
        public string NOMBRE { get; set; }
        public string RUBRO { get; set; }
        public string DIRECCION { get; set; }
        public int TELEFONO { get; set; }
        public decimal USUARIO { get; set; }
    
        public virtual USUARIO USUARIO1 { get; set; }
    }
}
