//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class HABITACION
    {
        public decimal IDHABITACION { get; set; }
        public decimal NUMERO { get; set; }
        public string TIPO_CAMA { get; set; }
        public string ACCESORIOS { get; set; }
        public int PRECIO { get; set; }
        public decimal IDADMINISTRADOR { get; set; }
        public decimal ESTADOHABITACION { get; set; }
    
        public virtual ADMINISTRADOR ADMINISTRADOR { get; set; }
        public virtual ESTADOHABITACION ESTADOHABITACION1 { get; set; }
    }
}
