//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIOCOMEDOR
    {
        public decimal IDSERVICIO { get; set; }
        public string PLATO { get; set; }
        public int PRECIO { get; set; }
        public decimal TIPOSERVICIO { get; set; }
        public decimal IDADMINISTRADOR { get; set; }
    
        public virtual ADMINISTRADOR ADMINISTRADOR { get; set; }
        public virtual TIPOSERVICIO TIPOSERVICIO1 { get; set; }
    }
}
