//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPOSERVICIO
    {
        public TIPOSERVICIO()
        {
            this.SERVICIOCOMEDOR = new HashSet<SERVICIOCOMEDOR>();
        }
    
        public decimal IDTIPO { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<SERVICIOCOMEDOR> SERVICIOCOMEDOR { get; set; }
    }
}
