//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.ADMINISTRADOR = new HashSet<ADMINISTRADOR>();
            this.CLIENTE = new HashSet<CLIENTE>();
            this.EMPLEADO = new HashSet<EMPLEADO>();
            this.PROVEEDOR = new HashSet<PROVEEDOR>();
        }
    
        public decimal IDUSUARIO { get; set; }
        public decimal TIPOUSUARIO { get; set; }
        public string USUARIO1 { get; set; }
        public string CONTRASEÑA { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO_PATERNO { get; set; }
        public string APELLIDO_MATERNO { get; set; }
        public string CORREO { get; set; }
    
        public virtual ICollection<ADMINISTRADOR> ADMINISTRADOR { get; set; }
        public virtual ICollection<CLIENTE> CLIENTE { get; set; }
        public virtual ICollection<EMPLEADO> EMPLEADO { get; set; }
        public virtual ICollection<PROVEEDOR> PROVEEDOR { get; set; }
        public virtual TIPOUSUARIO TIPOUSUARIO1 { get; set; }
    }
}
